config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }


  root 'pages#home'
  get '/home' => 'pages#home'
  get '/discover' => 'pages#discover'
  get '/browse' => 'pages#browse'
  get '/search' => 'pages#search'
  get '/about' => 'pages#about'
  get '/comics/for_bubbles' => 'comics#for_bubbles'


  resources :users
  resources :pages
  resources :users, only: [:show, :index, :destroy] 

  resources :albums
  resources :comics


 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comics
  has_many :albums
  accepts_nested_attributes_for :albums, allow_destroy: :false
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable,:omniauthable, omniauth_providers: [:facebook]
  mount_uploader :user_avatar, UserAvatarUploader

  before_save :set_default_user_role

  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
        user.first_name = auth.info.first_name
        user.provider   = auth.provider
        user.uid        = auth.uid
        user.email      = auth.info.email
        user.password   = Devise.friendly_token[0,20]
      end
    end
  end

  def name
    [first_name, last_name].delete_if(&:blank?).join(' ')
  end


  def role?(role_to_compare)
     self.role.to_s == role_to_compare.to_s
   end

   private
   def set_default_user_role
     self.role = "user" if self.role.nil?
   end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_resources, only: [:show, :edit]

  before_action :authenticate_user!

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to(@user)
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def set_resources
    @user = current_user
    # @user = User.find(params[:id])
    # @groups = Group.where
  end

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email, :user_avatar, :remote_user_avatar_url)
  end

end

app/views/users/_form.html.erb
<div>
  <%= f.text_field :first_name, placeholder: "First Name" %><br><br>
</div>
<div>
  <%= f.text_field :last_name, placeholder: "Last Name" %><br><br>
</div>
 <div>
  <%= f.label :user_avatar %><br>
  <%= f.file_field :user_avatar %><br><br>
</div>
 <div>
  <%= f.text_field :remote_user_avatar_url, placeholder: "Web URL for Picture" %>
</div>

app/views/users/edit.html.erb
<a href="#footer"><h1>EDIT PROFILE</h1></a>


<div class="module">
<%= form_for @user do |f| %>
<%= render partial: 'form', locals: { f: f } %><br>
<%= f.submit 'Edit Profile!' %>
<% end %>
</div>

app/views/users/show.html.erb
<a href="#footer"><h1 id="top" >Hello <%= @user.first_name%> <%= @user.last_name%></h1></a>


<div class="module">
    <% if @user.user_avatar.present? %>
    <%= link_to image_tag(@user.user_avatar.url, height: '60', width: '60'), @user.user_avatar.detail.url %>
    <% else %>
    <%= link_to image_tag("log_out.jpg", height: '60', width: '60') %>
    <% end %>
 
  <div>
    <%= link_to "Edit Profile", edit_user_path  %><br>
    <%= link_to "Edit Password", edit_user_registration_path %><br>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %><br><br>
  </div>  

  <div>
    <%= link_to 'Add New Album', new_album_path, class: 'button' %>
    <%= link_to 'Add New Comic', new_comic_path, class: 'button'  %>
  </div>
</div>

  <% @user.comics.each do |comic| %>
  <p>
    <div class="album_container"> 

      <% if comic.comic_image.present? %>
      <%= link_to image_tag(comic.comic_image.url, height: '160', width: '110', class: "album_float_left"), comic %><br>
      <% else %>
      <%= link_to image_tag("no_comic_cover.jpg", height: '160', width: '110', class: "album_float_left"), comic %><br>
      <% end %>
  </p>

    <div class="album_float_right">
     <strong><%= comic.name %></strong><br>
     issue #<%= comic.issue_number %><br><br>
     <%= link_to 'Edit', edit_comic_path(comic) if can? :edit, comic %>
     <%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } if can?(:destroy, comic)%>
     </div>
    </div>
  <% end %>

  <% @user.albums.each do |album| %>
    <p> 
      <div class="album_container"> 

        <% if album.album_image.present? %>
        <%= link_to image_tag(album.album_cover.url, height: '110', width: '110', height: '110', width: '110', class: "album_float_left"), album %><br>
        <% else %>
        <%= link_to image_tag("no_album_cover.jpg", height: '110', width: '110', class: "album_float_left"), album %><br>
        <% end %>    
      </p>

      <div class="album_float_right">
        <strong><%= album.name %></strong> <br>
        <%= album.comics.size %> items<br><br>
        <%= link_to 'Edit', edit_album_path(album) if can? :edit, album %>
        <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } if can?(:destroy, album)%>
      </div>
    </div>
  <% end %>
 