config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }


  root 'pages#home'
  get '/home' => 'pages#home'
  get '/discover' => 'pages#discover'
  get '/browse' => 'pages#browse'
  get '/search' => 'pages#search'
  get '/about' => 'pages#about'
  get '/comics/for_bubbles' => 'comics#for_bubbles'


  resources :users
  resources :pages
  resources :users, only: [:show, :index, :destroy] 

  resources :albums
  resources :comics


 
end

app/views/layouts/_navigation.html.erb
  <nav id="menu">
    
      <ul class="clearnav">
      <li>
     <%= link_to image_tag("home.jpg", height: '45', width: '45' ), home_path, class: 'Home', data: {tooltip: 'Home'} %>
      </li>
      <li><%= link_to image_tag("thor.jpg", height: '45', width: '45'), about_path, class: 'About', data: {tooltip: 'About'}  %>
      </li>
      <li><%= link_to image_tag("star.jpg", height: '45', width: '45'), discover_path, class: 'Discover', data: {tooltip: 'Discover'}  %>

      </li>
      <li><%= link_to image_tag("spidey1.jpg", height: '45', width: '45'), browse_path, class: 'Browse', data: {tooltip: 'Browse'}  %>

      </li>
      <% if current_user %>
        <li><%= link_to image_tag("log_out.jpg", height: '45', width: '45'), user_path(current_user), class: 'Profile', data: {tooltip: 'Profile'}  %>

        </li>
      <% else %>
        <li><%= link_to image_tag("log_in.jpg", height: '45', width: '45'), new_user_session_path, class: 'Log_in', data: {tooltip: 'Log_in'}  %></li>
       
      <% end %>
    </ul>
  
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comic Bubble</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'comic_bubble.icns' %>
    <%= favicon_link_tag 'comic_bubble.ico' %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
  
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <div class="push"></div>
    </main>
   <footer id='footer'>
      <%= render 'layouts/navigation' %>
    </footer>
    <%= javascript_include_tag 'application' %>
    <script src="https://connect.facebook.net/en_US/all.js"></script>
  </body>
</html>